thrift -out py_iface -gen py impression.thrift
thrift -out py_iface -gen py instance.thrift
thrift -out py_iface -gen py maitreya.thrift
thrift -out py_iface -gen py profile.thrift
thrift -out py_iface -gen py recommend.thrift
thrift -out py_iface -gen py unique.thrift
thrift -out py_iface -gen py lda.thrift
thrift -out py_iface -gen py profile_mp.thrift
thrift -out py_iface -gen py profile_kd.thrift
thrift -out py_iface -gen py follow.thrift
thrift -out py_iface -gen py audio_feature_extraction.thrift
thrift -out py_iface -gen py video_feature_extraction.thrift
thrift -out py_iface -gen py miaopai_predict.thrift
thrift -out py_iface -gen py vulgar_detect.thrift
thrift -out py_iface -gen py document_process.thrift
thrift -out py_iface -gen py wordcut.thrift
thrift -out py_iface -gen py video_word2vec.thrift
thrift -out py_iface -gen py idkv.thrift
thrift -out py_iface -gen py ad/ad_impression.thrift
thrift -out py_iface -gen py ad/ad_profile.thrift
thrift -out py_iface -gen py ad/ad_recommend.thrift
thrift -out py_iface -gen py ad/antispam.thrift
thrift -out py_iface -gen py ad/ad_broker.thrift
thrift -out py_iface -gen py ad/installation.thrift
thrift -out py_iface -gen py ad/ad_third_party.thrift
